CREATE TABLE IF NOT EXISTS pixon_data
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    hash CHAR(32) NOT NULL,
    `key` VARCHAR(128) NOT NULL,
    value VARCHAR(256) NOT NULL,
    `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    votes INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX (hash)
);
